language: objective-c 
osx_image: xcode7.2
xcode_project: ./Demo/MGCollapsibleHeaderDemo.xcodeproj
xcode_scheme: MGCollapsibleHeader
xcode_sdk: iphonesimulator9.2
cache:
- bundler
before_install:
- bundle install
- cd Demo && pod install