language: objective-c
cache:
- bundler
before_install:
- bundle install
- cd Demo && pod install && cd $TRAVIS_BUILD_DIR
script:
- xctool -workspace Demo/MGCollapsibleHeaderDemo.xcworkspace -scheme MGCollapsibleHeaderDemo -sdk iphonesimulator9.2 ONLY_ACTIVE_ARCH=NO
after_success: